apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: badal1/client

--- 
apiVersion: v1
kind: Service
metadata:
  name: clients-srv

spec:
  type: ClusterIP
  selector:
    app: clients
  ports:
  - name: clients
    protocol: TCP
    port: 5173
    targetPort: 5173